function getMimeType(fileName) {
    let extension = getFileExtension(fileName.toLowerCase())
    let resultType = "application/octet-stream"
    $.each(mimeTypesDB, (type, extensions) => {
        if (extensions.includes(extension))
            return (resultType = type)
    })
    if (resultType.startsWith('text'))
        resultType += ';charset=utf-8'
    
    return resultType
}
function getFileExtension(fileName) {
    const parts = fileName.split(".")
    return parts[parts.length - 1]
}

var mimeTypesDB = {
    'application/1d-interleaved-parityfec': ['1d-interleaved-parityfec'],
    'application/3gpdash-qoe-report+xml': ['3gpdash-qoe-report+xml'],
    'application/3gpp-ims+xml': ['3gpp-ims+xml'],
    'application/3gpphal+json': ['3gpphal+json'],
    'application/3gpphalforms+json': ['3gpphalforms+json'],
    'application/a2l': ['a2l'],
    'application/ace+cbor': ['ace+cbor'],
    'application/ace+json': ['ace+json'],
    'application/activemessage': ['activemessage'],
    'application/activity+json': ['activity+json'],
    'application/aif+cbor': ['aif+cbor'],
    'application/aif+json': ['aif+json'],
    'application/alto-cdni+json': ['alto-cdni+json'],
    'application/alto-cdnifilter+json': ['alto-cdnifilter+json'],
    'application/alto-costmap+json': ['alto-costmap+json'],
    'application/alto-costmapfilter+json': ['alto-costmapfilter+json'],
    'application/alto-directory+json': ['alto-directory+json'],
    'application/alto-endpointcost+json': ['alto-endpointcost+json'],
    'application/alto-endpointcostparams+json': ['alto-endpointcostparams+json'],
    'application/alto-endpointprop+json': ['alto-endpointprop+json'],
    'application/alto-endpointpropparams+json': ['alto-endpointpropparams+json'],
    'application/alto-error+json': ['alto-error+json'],
    'application/alto-networkmap+json': ['alto-networkmap+json'],
    'application/alto-networkmapfilter+json': ['alto-networkmapfilter+json'],
    'application/alto-propmap+json': ['alto-propmap+json'],
    'application/alto-propmapparams+json': ['alto-propmapparams+json'],
    'application/alto-updatestreamcontrol+json': ['alto-updatestreamcontrol+json'],
    'application/alto-updatestreamparams+json': ['alto-updatestreamparams+json'],
    'application/aml': ['aml'],
    'application/andrew-inset': ['andrew-inset', 'ez'],
    'application/applefile': ['applefile'],
    'application/applixware': ['aw'],
    'application/at+jwt': ['at+jwt'],
    'application/atf': ['atf'],
    'application/atfx': ['atfx'],
    'application/atom+xml': ['atom+xml', 'atom'],
    'application/atomcat+xml': ['atomcat+xml', 'atomcat'],
    'application/atomdeleted+xml': ['atomdeleted+xml', 'atomdeleted'],
    'application/atomicmail': ['atomicmail'],
    'application/atomsvc+xml': ['atomsvc+xml', 'atomsvc'],
    'application/atsc-dwd+xml': ['atsc-dwd+xml', 'dwd'],
    'application/atsc-dynamic-event-message': ['atsc-dynamic-event-message'],
    'application/atsc-held+xml': ['atsc-held+xml', 'held'],
    'application/atsc-rdt+json': ['atsc-rdt+json'],
    'application/atsc-rsat+xml': ['atsc-rsat+xml', 'rsat'],
    'application/atxml': ['atxml'],
    'application/auth-policy+xml': ['auth-policy+xml'],
    'application/automationml-aml+xml': ['automationml-aml+xml'],
    'application/automationml-amlx+zip': ['automationml-amlx+zip'],
    'application/bacnet-xdd+zip': ['bacnet-xdd+zip'],
    'application/batch-smtp': ['batch-smtp'],
    'application/bdoc': ['bdoc'],
    'application/beep+xml': ['beep+xml'],
    'application/calendar+json': ['calendar+json'],
    'application/calendar+xml': ['calendar+xml', 'xcs'],
    'application/call-completion': ['call-completion'],
    'application/cals-1840': ['cals-1840'],
    'application/captive+json': ['captive+json'],
    'application/cbor': ['cbor'],
    'application/cbor-seq': ['cbor-seq'],
    'application/cccex': ['cccex'],
    'application/ccmp+xml': ['ccmp+xml'],
    'application/ccxml+xml': ['ccxml+xml', 'ccxml'],
    'application/cda+xml': ['cda+xml'],
    'application/cdfx+xml': ['cdfx+xml', 'cdfx'],
    'application/cdmi-capability': ['cdmi-capability', 'cdmia'],
    'application/cdmi-container': ['cdmi-container', 'cdmic'],
    'application/cdmi-domain': ['cdmi-domain', 'cdmid'],
    'application/cdmi-object': ['cdmi-object', 'cdmio'],
    'application/cdmi-queue': ['cdmi-queue', 'cdmiq'],
    'application/cdni': ['cdni'],
    'application/cea': ['cea'],
    'application/cea-2018+xml': ['cea-2018+xml'],
    'application/cellml+xml': ['cellml+xml'],
    'application/cfw': ['cfw'],
    'application/city+json': ['city+json'],
    'application/clr': ['clr'],
    'application/clue+xml': ['clue+xml'],
    'application/clue_info+xml': ['clue_info+xml'],
    'application/cms': ['cms'],
    'application/cnrp+xml': ['cnrp+xml'],
    'application/coap-group+json': ['coap-group+json'],
    'application/coap-payload': ['coap-payload'],
    'application/commonground': ['commonground'],
    'application/concise-problem-details+cbor': ['concise-problem-details+cbor'],
    'application/conference-info+xml': ['conference-info+xml'],
    'application/cose': ['cose'],
    'application/cose-key': ['cose-key'],
    'application/cose-key-set': ['cose-key-set'],
    'application/cose-x509': ['cose-x509'],
    'application/cpl+xml': ['cpl+xml', 'cpl'],
    'application/csrattrs': ['csrattrs'],
    'application/csta+xml': ['csta+xml'],
    'application/cstadata+xml': ['cstadata+xml'],
    'application/csvm+json': ['csvm+json'],
    'application/cu-seeme': ['cu'],
    'application/cwl': ['cwl'],
    'application/cwl+json': ['cwl+json'],
    'application/cwt': ['cwt'],
    'application/cybercash': ['cybercash'],
    'application/dash+xml': ['dash+xml', 'mpd'],
    'application/dash-patch+xml': ['dash-patch+xml', 'mpp'],
    'application/dashdelta': ['dashdelta'],
    'application/davmount+xml': ['davmount+xml', 'davmount'],
    'application/dca-rft': ['dca-rft'],
    'application/dcd': ['dcd'],
    'application/dec-dx': ['dec-dx'],
    'application/dialog-info+xml': ['dialog-info+xml'],
    'application/dicom': ['dicom'],
    'application/dicom+json': ['dicom+json'],
    'application/dicom+xml': ['dicom+xml'],
    'application/dii': ['dii'],
    'application/dit': ['dit'],
    'application/dns': ['dns'],
    'application/dns+json': ['dns+json'],
    'application/dns-message': ['dns-message'],
    'application/docbook+xml': ['dbk'],
    'application/dots+cbor': ['dots+cbor'],
    'application/dpop+jwt': ['dpop+jwt'],
    'application/dskpp+xml': ['dskpp+xml'],
    'application/dssc+der': ['dssc+der', 'dssc'],
    'application/dssc+xml': ['dssc+xml', 'xdssc'],
    'application/dvcs': ['dvcs'],
    'application/ecmascript': ['es', 'ecma'],
    'application/edi-consent': ['edi-consent'],
    'application/edi-x12': ['edi-x12'],
    'application/edifact': ['edifact'],
    'application/efi': ['efi'],
    'application/elm+json': ['elm+json'],
    'application/elm+xml': ['elm+xml'],
    'application/emergencycalldata.cap+xml': ['emergencycalldata.cap+xml'],
    'application/emergencycalldata.comment+xml': ['emergencycalldata.comment+xml'],
    'application/emergencycalldata.control+xml': ['emergencycalldata.control+xml'],
    'application/emergencycalldata.deviceinfo+xml': ['emergencycalldata.deviceinfo+xml'],
    'application/emergencycalldata.ecall.msd': ['emergencycalldata.ecall.msd'],
    'application/emergencycalldata.legacyesn+json': ['emergencycalldata.legacyesn+json'],
    'application/emergencycalldata.providerinfo+xml': ['emergencycalldata.providerinfo+xml'],
    'application/emergencycalldata.serviceinfo+xml': ['emergencycalldata.serviceinfo+xml'],
    'application/emergencycalldata.subscriberinfo+xml': ['emergencycalldata.subscriberinfo+xml'],
    'application/emergencycalldata.veds+xml': ['emergencycalldata.veds+xml'],
    'application/emma+xml': ['emma+xml', 'emma'],
    'application/emotionml+xml': ['emotionml+xml', 'emotionml'],
    'application/encaprtp': ['encaprtp'],
    'application/epp+xml': ['epp+xml'],
    'application/epub+zip': ['epub+zip', 'epub'],
    'application/eshop': ['eshop'],
    'application/example': ['example'],
    'application/exi': ['exi'],
    'application/expect-ct-report+json': ['expect-ct-report+json'],
    'application/express': ['express', 'exp'],
    'application/fastinfoset': ['fastinfoset'],
    'application/fastsoap': ['fastsoap'],
    'application/fdf': ['fdf'],
    'application/fdt+xml': ['fdt+xml', 'fdt'],
    'application/fhir+json': ['fhir+json'],
    'application/fhir+xml': ['fhir+xml'],
    'application/fits': ['fits'],
    'application/flexfec': ['flexfec'],
    'application/font-tdpfr': ['font-tdpfr', 'pfr'],
    'application/framework-attributes+xml': ['framework-attributes+xml'],
    'application/geo+json': ['geo+json', 'geojson'],
    'application/geo+json-seq': ['geo+json-seq'],
    'application/geopackage+sqlite3': ['geopackage+sqlite3'],
    'application/geoxacml+xml': ['geoxacml+xml'],
    'application/gltf-buffer': ['gltf-buffer'],
    'application/gml+xml': ['gml+xml', 'gml'],
    'application/gpx+xml': ['gpx'],
    'application/gxf': ['gxf'],
    'application/gzip': ['gzip', 'gz'],
    'application/h224': ['h224'],
    'application/held+xml': ['held+xml'],
    'application/hjson': ['hjson'],
    'application/hl7v2+xml': ['hl7v2+xml'],
    'application/http': ['http'],
    'application/hyperstudio': ['hyperstudio', 'stk'],
    'application/ibe-key-request+xml': ['ibe-key-request+xml'],
    'application/ibe-pkg-reply+xml': ['ibe-pkg-reply+xml'],
    'application/ibe-pp-data': ['ibe-pp-data'],
    'application/iges': ['iges'],
    'application/im-iscomposing+xml': ['im-iscomposing+xml'],
    'application/index': ['index'],
    'application/index.cmd': ['index.cmd'],
    'application/index.obj': ['index.obj'],
    'application/index.response': ['index.response'],
    'application/index.vnd': ['index.vnd'],
    'application/inkml+xml': ['inkml+xml', 'ink', 'inkml'],
    'application/iotp': ['iotp'],
    'application/ipfix': ['ipfix'],
    'application/ipp': ['ipp'],
    'application/isup': ['isup'],
    'application/its+xml': ['its+xml', 'its'],
    'application/java-archive': ['java-archive', 'jar', 'war', 'ear'],
    'application/java-serialized-object': ['ser'],
    'application/java-vm': ['class'],
    'application/javascript': ['js', 'mjs'],
    'application/jf2feed+json': ['jf2feed+json'],
    'application/jose': ['jose'],
    'application/jose+json': ['jose+json'],
    'application/jrd+json': ['jrd+json'],
    'application/jscalendar+json': ['jscalendar+json'],
    'application/json': ['json', 'map'],
    'application/json-patch+json': ['json-patch+json'],
    'application/json-seq': ['json-seq'],
    'application/json5': ['json5'],
    'application/jsonml+json': ['jsonml'],
    'application/jwk+json': ['jwk+json'],
    'application/jwk-set+json': ['jwk-set+json'],
    'application/jwt': ['jwt'],
    'application/kpml-request+xml': ['kpml-request+xml'],
    'application/kpml-response+xml': ['kpml-response+xml'],
    'application/ld+json': ['ld+json', 'jsonld'],
    'application/lgr+xml': ['lgr+xml', 'lgr'],
    'application/link-format': ['link-format'],
    'application/linkset': ['linkset'],
    'application/linkset+json': ['linkset+json'],
    'application/load-control+xml': ['load-control+xml'],
    'application/logout+jwt': ['logout+jwt'],
    'application/lost+xml': ['lost+xml', 'lostxml'],
    'application/lostsync+xml': ['lostsync+xml'],
    'application/lpf+zip': ['lpf+zip'],
    'application/lxf': ['lxf'],
    'application/mac-binhex40': ['mac-binhex40', 'hqx'],
    'application/mac-compactpro': ['cpt'],
    'application/macwriteii': ['macwriteii'],
    'application/mads+xml': ['mads+xml', 'mads'],
    'application/manifest+json': ['manifest+json', 'webmanifest'],
    'application/marc': ['marc', 'mrc'],
    'application/marcxml+xml': ['marcxml+xml', 'mrcx'],
    'application/mathematica': ['mathematica', 'ma', 'nb', 'mb'],
    'application/mathml+xml': ['mathml+xml', 'mathml'],
    'application/mathml-content+xml': ['mathml-content+xml'],
    'application/mathml-presentation+xml': ['mathml-presentation+xml'],
    'application/mbms-associated-procedure-description+xml': ['mbms-associated-procedure-description+xml'],
    'application/mbms-deregister+xml': ['mbms-deregister+xml'],
    'application/mbms-envelope+xml': ['mbms-envelope+xml'],
    'application/mbms-msk+xml': ['mbms-msk+xml'],
    'application/mbms-msk-response+xml': ['mbms-msk-response+xml'],
    'application/mbms-protection-description+xml': ['mbms-protection-description+xml'],
    'application/mbms-reception-report+xml': ['mbms-reception-report+xml'],
    'application/mbms-register+xml': ['mbms-register+xml'],
    'application/mbms-register-response+xml': ['mbms-register-response+xml'],
    'application/mbms-schedule+xml': ['mbms-schedule+xml'],
    'application/mbms-user-service-description+xml': ['mbms-user-service-description+xml'],
    'application/mbox': ['mbox'],
    'application/media-policy-dataset+xml': ['media-policy-dataset+xml', 'mpf'],
    'application/media_control+xml': ['media_control+xml'],
    'application/mediaservercontrol+xml': ['mediaservercontrol+xml', 'mscml'],
    'application/merge-patch+json': ['merge-patch+json'],
    'application/metalink+xml': ['metalink'],
    'application/metalink4+xml': ['metalink4+xml', 'meta4'],
    'application/mets+xml': ['mets+xml', 'mets'],
    'application/mf4': ['mf4'],
    'application/mikey': ['mikey'],
    'application/mipc': ['mipc'],
    'application/missing-blocks+cbor-seq': ['missing-blocks+cbor-seq'],
    'application/mmt-aei+xml': ['mmt-aei+xml', 'maei'],
    'application/mmt-usd+xml': ['mmt-usd+xml', 'musd'],
    'application/mods+xml': ['mods+xml', 'mods'],
    'application/moss-keys': ['moss-keys'],
    'application/moss-signature': ['moss-signature'],
    'application/mosskey-data': ['mosskey-data'],
    'application/mosskey-request': ['mosskey-request'],
    'application/mp21': ['mp21', 'm21'],
    'application/mp4': ['mp4', 'mp4s', 'm4p'],
    'application/mpeg4-generic': ['mpeg4-generic'],
    'application/mpeg4-iod': ['mpeg4-iod'],
    'application/mpeg4-iod-xmt': ['mpeg4-iod-xmt'],
    'application/mrb-consumer+xml': ['mrb-consumer+xml'],
    'application/mrb-publish+xml': ['mrb-publish+xml'],
    'application/msc-ivr+xml': ['msc-ivr+xml'],
    'application/msc-mixer+xml': ['msc-mixer+xml'],
    'application/msword': ['msword', 'doc', 'dot', 'wiz'],
    'application/mud+json': ['mud+json'],
    'application/multipart-core': ['multipart-core'],
    'application/mxf': ['mxf'],
    'application/n-quads': ['n-quads', 'nq'],
    'application/n-triples': ['n-triples', 'nt'],
    'application/nasdata': ['nasdata'],
    'application/news-checkgroups': ['news-checkgroups'],
    'application/news-groupinfo': ['news-groupinfo'],
    'application/news-transmission': ['news-transmission'],
    'application/nlsml+xml': ['nlsml+xml'],
    'application/node': ['node', 'cjs'],
    'application/nss': ['nss'],
    'application/oauth-authz-req+jwt': ['oauth-authz-req+jwt'],
    'application/oblivious-dns-message': ['oblivious-dns-message'],
    'application/ocsp-request': ['ocsp-request'],
    'application/ocsp-response': ['ocsp-response'],
    'application/octet-stream': ['octet-stream',
                                'bin',
                                'a',
                                'dll',
                                'exe',
                                'o',
                                'obj',
                                'so',
                                'dms',
                                'lrf',
                                'mar',
                                'dist',
                                'distz',
                                'pkg',
                                'bpk',
                                'dump',
                                'elc',
                                'deploy',
                                'deb',
                                'dmg',
                                'iso',
                                'img',
                                'msi',
                                'msp',
                                'msm',
                                'buffer'],
    'application/oda': ['oda'],
    'application/odm+xml': ['odm+xml'],
    'application/odx': ['odx'],
    'application/oebps-package+xml': ['oebps-package+xml', 'opf'],
    'application/ogg': ['ogg', 'ogx'],
    'application/ohttp-keys': ['ohttp-keys'],
    'application/omdoc+xml': ['omdoc'],
    'application/onenote': ['onetoc', 'onetoc2', 'onetmp', 'onepkg'],
    'application/opc-nodeset+xml': ['opc-nodeset+xml'],
    'application/oscore': ['oscore'],
    'application/oxps': ['oxps'],
    'application/p21': ['p21'],
    'application/p21+zip': ['p21+zip'],
    'application/p2p-overlay+xml': ['p2p-overlay+xml', 'relo'],
    'application/parityfec': ['parityfec'],
    'application/passport': ['passport'],
    'application/patch-ops-error+xml': ['patch-ops-error+xml', 'xer'],
    'application/pdf': ['pdf'],
    'application/pdx': ['pdx'],
    'application/pem-certificate-chain': ['pem-certificate-chain'],
    'application/pgp-encrypted': ['pgp-encrypted', 'pgp'],
    'application/pgp-keys': ['pgp-keys', 'asc'],
    'application/pgp-signature': ['pgp-signature', 'asc', 'sig'],
    'application/pics-rules': ['prf'],
    'application/pidf+xml': ['pidf+xml'],
    'application/pidf-diff+xml': ['pidf-diff+xml'],
    'application/pkcs10': ['pkcs10', 'p10'],
    'application/pkcs12': ['pkcs12'],
    'application/pkcs7-mime': ['pkcs7-mime', 'p7c', 'p7m'],
    'application/pkcs7-signature': ['pkcs7-signature', 'p7s'],
    'application/pkcs8': ['pkcs8', 'p8'],
    'application/pkcs8-encrypted': ['pkcs8-encrypted'],
    'application/pkix-attr-cert': ['pkix-attr-cert', 'ac'],
    'application/pkix-cert': ['pkix-cert', 'cer'],
    'application/pkix-crl': ['pkix-crl', 'crl'],
    'application/pkix-pkipath': ['pkix-pkipath', 'pkipath'],
    'application/pkixcmp': ['pkixcmp', 'pki'],
    'application/pls+xml': ['pls+xml', 'pls'],
    'application/poc-settings+xml': ['poc-settings+xml'],
    'application/postscript': ['postscript', 'ps', 'ai', 'eps'],
    'application/ppsp-tracker+json': ['ppsp-tracker+json'],
    'application/problem+json': ['problem+json'],
    'application/problem+xml': ['problem+xml'],
    'application/provenance+xml': ['provenance+xml', 'provx'],
    'application/prs.alvestrand.titrax-sheet': ['prs.alvestrand.titrax-sheet'],
    'application/prs.cww': ['prs.cww', 'cww'],
    'application/prs.cyn': ['prs.cyn'],
    'application/prs.hpub+zip': ['prs.hpub+zip'],
    'application/prs.implied-document+xml': ['prs.implied-document+xml'],
    'application/prs.implied-executable': ['prs.implied-executable'],
    'application/prs.implied-structure': ['prs.implied-structure'],
    'application/prs.nprend': ['prs.nprend'],
    'application/prs.plucker': ['prs.plucker'],
    'application/prs.rdf-xml-crypt': ['prs.rdf-xml-crypt'],
    'application/prs.xsf+xml': ['prs.xsf+xml'],
    'application/pskc+xml': ['pskc+xml', 'pskcxml'],
    'application/pvd+json': ['pvd+json'],
    'application/qsig': ['qsig'],
    'application/raml+yaml': ['raml'],
    'application/raptorfec': ['raptorfec'],
    'application/rdap+json': ['rdap+json'],
    'application/rdf+xml': ['rdf+xml', 'rdf', 'owl'],
    'application/reginfo+xml': ['reginfo+xml', 'rif'],
    'application/relax-ng-compact-syntax': ['relax-ng-compact-syntax', 'rnc'],
    'application/reputon+json': ['reputon+json'],
    'application/resource-lists+xml': ['resource-lists+xml', 'rl'],
    'application/resource-lists-diff+xml': ['resource-lists-diff+xml', 'rld'],
    'application/rfc+xml': ['rfc+xml'],
    'application/riscos': ['riscos'],
    'application/rlmi+xml': ['rlmi+xml'],
    'application/rls-services+xml': ['rls-services+xml', 'rs'],
    'application/route-apd+xml': ['route-apd+xml', 'rapd'],
    'application/route-s-tsid+xml': ['route-s-tsid+xml', 'sls'],
    'application/route-usd+xml': ['route-usd+xml', 'rusd'],
    'application/rpki-checklist': ['rpki-checklist'],
    'application/rpki-ghostbusters': ['rpki-ghostbusters', 'gbr'],
    'application/rpki-manifest': ['rpki-manifest', 'mft'],
    'application/rpki-publication': ['rpki-publication'],
    'application/rpki-roa': ['rpki-roa', 'roa'],
    'application/rpki-updown': ['rpki-updown'],
    'application/rsd+xml': ['rsd'],
    'application/rss+xml': ['rss'],
    'application/rtf': ['rtf'],
    'application/rtploopback': ['rtploopback'],
    'application/rtx': ['rtx'],
    'application/samlassertion+xml': ['samlassertion+xml'],
    'application/samlmetadata+xml': ['samlmetadata+xml'],
    'application/sarif+json': ['sarif+json'],
    'application/sarif-external-properties+json': ['sarif-external-properties+json'],
    'application/sbe': ['sbe'],
    'application/sbml+xml': ['sbml+xml', 'sbml'],
    'application/scaip+xml': ['scaip+xml'],
    'application/scim+json': ['scim+json'],
    'application/scvp-cv-request': ['scvp-cv-request', 'scq'],
    'application/scvp-cv-response': ['scvp-cv-response', 'scs'],
    'application/scvp-vp-request': ['scvp-vp-request', 'spq'],
    'application/scvp-vp-response': ['scvp-vp-response', 'spp'],
    'application/sdp': ['sdp'],
    'application/secevent+jwt': ['secevent+jwt'],
    'application/senml+cbor': ['senml+cbor'],
    'application/senml+json': ['senml+json'],
    'application/senml+xml': ['senml+xml', 'senmlx'],
    'application/senml-etch+cbor': ['senml-etch+cbor'],
    'application/senml-etch+json': ['senml-etch+json'],
    'application/senml-exi': ['senml-exi'],
    'application/sensml+cbor': ['sensml+cbor'],
    'application/sensml+json': ['sensml+json'],
    'application/sensml+xml': ['sensml+xml', 'sensmlx'],
    'application/sensml-exi': ['sensml-exi'],
    'application/sep+xml': ['sep+xml'],
    'application/sep-exi': ['sep-exi'],
    'application/session-info': ['session-info'],
    'application/set-payment': ['set-payment'],
    'application/set-payment-initiation': ['set-payment-initiation', 'setpay'],
    'application/set-registration': ['set-registration'],
    'application/set-registration-initiation': ['set-registration-initiation',
                                                'setreg'],
    'application/sgml': ['sgml'],
    'application/sgml-open-catalog': ['sgml-open-catalog'],
    'application/shf+xml': ['shf+xml', 'shf'],
    'application/sieve': ['sieve', 'siv'],
    'application/simple-filter+xml': ['simple-filter+xml'],
    'application/simple-message-summary': ['simple-message-summary'],
    'application/simplesymbolcontainer': ['simplesymbolcontainer'],
    'application/sipc': ['sipc'],
    'application/slate': ['slate'],
    'application/smil+xml': ['smil+xml', 'smi', 'smil'],
    'application/smpte336m': ['smpte336m'],
    'application/soap+fastinfoset': ['soap+fastinfoset'],
    'application/soap+xml': ['soap+xml'],
    'application/sparql-query': ['sparql-query', 'rq'],
    'application/sparql-results+xml': ['sparql-results+xml', 'srx'],
    'application/spdx+json': ['spdx+json'],
    'application/spirits-event+xml': ['spirits-event+xml'],
    'application/sql': ['sql'],
    'application/srgs': ['srgs', 'gram'],
    'application/srgs+xml': ['srgs+xml', 'grxml'],
    'application/sru+xml': ['sru+xml', 'sru'],
    'application/ssdl+xml': ['ssdl'],
    'application/ssml+xml': ['ssml+xml', 'ssml'],
    'application/stix+json': ['stix+json'],
    'application/swid+cbor': ['swid+cbor'],
    'application/swid+xml': ['swid+xml', 'swidtag'],
    'application/tamp-apex-update': ['tamp-apex-update'],
    'application/tamp-apex-update-confirm': ['tamp-apex-update-confirm'],
    'application/tamp-community-update': ['tamp-community-update'],
    'application/tamp-community-update-confirm': ['tamp-community-update-confirm'],
    'application/tamp-error': ['tamp-error'],
    'application/tamp-sequence-adjust': ['tamp-sequence-adjust'],
    'application/tamp-sequence-adjust-confirm': ['tamp-sequence-adjust-confirm'],
    'application/tamp-status-query': ['tamp-status-query'],
    'application/tamp-status-response': ['tamp-status-response'],
    'application/tamp-update': ['tamp-update'],
    'application/tamp-update-confirm': ['tamp-update-confirm'],
    'application/taxii+json': ['taxii+json'],
    'application/td+json': ['td+json'],
    'application/tei+xml': ['tei+xml', 'tei', 'teicorpus'],
    'application/tetra_isi': ['tetra_isi'],
    'application/thraud+xml': ['thraud+xml', 'tfi'],
    'application/timestamp-query': ['timestamp-query'],
    'application/timestamp-reply': ['timestamp-reply'],
    'application/timestamped-data': ['timestamped-data', 'tsd'],
    'application/tlsrpt+gzip': ['tlsrpt+gzip'],
    'application/tlsrpt+json': ['tlsrpt+json'],
    'application/tm+json': ['tm+json'],
    'application/tnauthlist': ['tnauthlist'],
    'application/token-introspection+jwt': ['token-introspection+jwt'],
    'application/toml': ['toml'],
    'application/trickle-ice-sdpfrag': ['trickle-ice-sdpfrag'],
    'application/trig': ['trig'],
    'application/ttml+xml': ['ttml+xml', 'ttml'],
    'application/tve-trigger': ['tve-trigger'],
    'application/tzif': ['tzif'],
    'application/tzif-leap': ['tzif-leap'],
    'application/ubjson': ['ubj'],
    'application/ulpfec': ['ulpfec'],
    'application/urc-grpsheet+xml': ['urc-grpsheet+xml'],
    'application/urc-ressheet+xml': ['urc-ressheet+xml', 'rsheet'],
    'application/urc-targetdesc+xml': ['urc-targetdesc+xml', 'td'],
    'application/urc-uisocketdesc+xml': ['urc-uisocketdesc+xml'],
    'application/vcard+json': ['vcard+json'],
    'application/vcard+xml': ['vcard+xml'],
    'application/vemmi': ['vemmi'],
    'application/vnd.1000minds.decision-model+xml': ['1km'],
    'application/vnd.3gpp.pic-bw-large': ['plb'],
    'application/vnd.3gpp.pic-bw-small': ['psb'],
    'application/vnd.3gpp.pic-bw-var': ['pvb'],
    'application/vnd.3gpp2.tcap': ['tcap'],
    'application/vnd.3m.post-it-notes': ['pwn'],
    'application/vnd.accpac.simply.aso': ['aso'],
    'application/vnd.accpac.simply.imp': ['imp'],
    'application/vnd.acucobol': ['acu'],
    'application/vnd.acucorp': ['atc', 'acutc'],
    'application/vnd.adobe.air-application-installer-package+zip': ['air'],
    'application/vnd.adobe.formscentral.fcdt': ['fcdt'],
    'application/vnd.adobe.fxp': ['fxp', 'fxpl'],
    'application/vnd.adobe.xdp+xml': ['xdp'],
    'application/vnd.adobe.xfdf': ['xfdf'],
    'application/vnd.age': ['age'],
    'application/vnd.ahead.space': ['ahead'],
    'application/vnd.airzip.filesecure.azf': ['azf'],
    'application/vnd.airzip.filesecure.azs': ['azs'],
    'application/vnd.amazon.ebook': ['azw'],
    'application/vnd.americandynamics.acc': ['acc'],
    'application/vnd.amiga.ami': ['ami'],
    'application/vnd.android.package-archive': ['apk'],
    'application/vnd.anser-web-certificate-issue-initiation': ['cii'],
    'application/vnd.anser-web-funds-transfer-initiation': ['fti'],
    'application/vnd.antix.game-component': ['atx'],
    'application/vnd.apple.installer+xml': ['mpkg'],
    'application/vnd.apple.keynote': ['key'],
    'application/vnd.apple.mpegurl': ['m3u', 'm3u8'],
    'application/vnd.apple.numbers': ['numbers'],
    'application/vnd.apple.pages': ['pages'],
    'application/vnd.apple.pkpass': ['pkpass'],
    'application/vnd.aristanetworks.swi': ['swi'],
    'application/vnd.astraea-software.iota': ['iota'],
    'application/vnd.audiograph': ['aep'],
    'application/vnd.balsamiq.bmml+xml': ['bmml'],
    'application/vnd.blueice.multipass': ['mpm'],
    'application/vnd.bmi': ['bmi'],
    'application/vnd.businessobjects': ['rep'],
    'application/vnd.chemdraw+xml': ['cdxml'],
    'application/vnd.chipnuts.karaoke-mmd': ['mmd'],
    'application/vnd.cinderella': ['cdy'],
    'application/vnd.citationstyles.style+xml': ['csl'],
    'application/vnd.claymore': ['cla'],
    'application/vnd.cloanto.rp9': ['rp9'],
    'application/vnd.clonk.c4group': ['c4g', 'c4d', 'c4f', 'c4p', 'c4u'],
    'application/vnd.cluetrust.cartomobile-config': ['c11amc'],
    'application/vnd.cluetrust.cartomobile-config-pkg': ['c11amz'],
    'application/vnd.commonspace': ['csp'],
    'application/vnd.contact.cmsg': ['cdbcmsg'],
    'application/vnd.cosmocaller': ['cmc'],
    'application/vnd.crick.clicker': ['clkx'],
    'application/vnd.crick.clicker.keyboard': ['clkk'],
    'application/vnd.crick.clicker.palette': ['clkp'],
    'application/vnd.crick.clicker.template': ['clkt'],
    'application/vnd.crick.clicker.wordbank': ['clkw'],
    'application/vnd.criticaltools.wbs+xml': ['wbs'],
    'application/vnd.ctc-posml': ['pml'],
    'application/vnd.cups-ppd': ['ppd'],
    'application/vnd.curl.car': ['car'],
    'application/vnd.curl.pcurl': ['pcurl'],
    'application/vnd.dart': ['dart'],
    'application/vnd.data-vision.rdz': ['rdz'],
    'application/vnd.dbf': ['dbf'],
    'application/vnd.dece.data': ['uvf', 'uvvf', 'uvd', 'uvvd'],
    'application/vnd.dece.ttml+xml': ['uvt', 'uvvt'],
    'application/vnd.dece.unspecified': ['uvx', 'uvvx'],
    'application/vnd.dece.zip': ['uvz', 'uvvz'],
    'application/vnd.denovo.fcselayout-link': ['fe_launch'],
    'application/vnd.dna': ['dna'],
    'application/vnd.dolby.mlp': ['mlp'],
    'application/vnd.dpgraph': ['dpg'],
    'application/vnd.dreamfactory': ['dfac'],
    'application/vnd.ds-keypoint': ['kpxx'],
    'application/vnd.dvb.ait': ['ait'],
    'application/vnd.dvb.service': ['svc'],
    'application/vnd.dynageo': ['geo'],
    'application/vnd.ecowin.chart': ['mag'],
    'application/vnd.enliven': ['nml'],
    'application/vnd.epson.esf': ['esf'],
    'application/vnd.epson.msf': ['msf'],
    'application/vnd.epson.quickanime': ['qam'],
    'application/vnd.epson.salt': ['slt'],
    'application/vnd.epson.ssf': ['ssf'],
    'application/vnd.eszigno3+xml': ['es3', 'et3'],
    'application/vnd.ezpix-album': ['ez2'],
    'application/vnd.ezpix-package': ['ez3'],
    'application/vnd.fdf': ['fdf'],
    'application/vnd.fdsn.mseed': ['mseed'],
    'application/vnd.fdsn.seed': ['seed', 'dataless'],
    'application/vnd.flographit': ['gph'],
    'application/vnd.fluxtime.clip': ['ftc'],
    'application/vnd.framemaker': ['fm', 'frame', 'maker', 'book'],
    'application/vnd.frogans.fnc': ['fnc'],
    'application/vnd.frogans.ltf': ['ltf'],
    'application/vnd.fsc.weblaunch': ['fsc'],
    'application/vnd.fujitsu.oasys': ['oas'],
    'application/vnd.fujitsu.oasys2': ['oa2'],
    'application/vnd.fujitsu.oasys3': ['oa3'],
    'application/vnd.fujitsu.oasysgp': ['fg5'],
    'application/vnd.fujitsu.oasysprs': ['bh2'],
    'application/vnd.fujixerox.ddd': ['ddd'],
    'application/vnd.fujixerox.docuworks': ['xdw'],
    'application/vnd.fujixerox.docuworks.binder': ['xbd'],
    'application/vnd.fuzzysheet': ['fzs'],
    'application/vnd.genomatix.tuxedo': ['txd'],
    'application/vnd.geogebra.file': ['ggb'],
    'application/vnd.geogebra.tool': ['ggt'],
    'application/vnd.geometry-explorer': ['gex', 'gre'],
    'application/vnd.geonext': ['gxt'],
    'application/vnd.geoplan': ['g2w'],
    'application/vnd.geospace': ['g3w'],
    'application/vnd.gmx': ['gmx'],
    'application/vnd.google-apps.document': ['gdoc'],
    'application/vnd.google-apps.presentation': ['gslides'],
    'application/vnd.google-apps.spreadsheet': ['gsheet'],
    'application/vnd.google-earth.kml+xml': ['kml'],
    'application/vnd.google-earth.kmz': ['kmz'],
    'application/vnd.grafeq': ['gqf', 'gqs'],
    'application/vnd.groove-account': ['gac'],
    'application/vnd.groove-help': ['ghf'],
    'application/vnd.groove-identity-message': ['gim'],
    'application/vnd.groove-injector': ['grv'],
    'application/vnd.groove-tool-message': ['gtm'],
    'application/vnd.groove-tool-template': ['tpl'],
    'application/vnd.groove-vcard': ['vcg'],
    'application/vnd.hal+xml': ['hal'],
    'application/vnd.handheld-entertainment+xml': ['zmm'],
    'application/vnd.hbci': ['hbci'],
    'application/vnd.hhe.lesson-player': ['les'],
    'application/vnd.hp-hpgl': ['hpgl'],
    'application/vnd.hp-hpid': ['hpid'],
    'application/vnd.hp-hps': ['hps'],
    'application/vnd.hp-jlyt': ['jlt'],
    'application/vnd.hp-pcl': ['pcl'],
    'application/vnd.hp-pclxl': ['pclxl'],
    'application/vnd.hydrostatix.sof-data': ['sfd-hdstx'],
    'application/vnd.ibm.minipay': ['mpy'],
    'application/vnd.ibm.modcap': ['afp', 'listafp', 'list3820'],
    'application/vnd.ibm.rights-management': ['irm'],
    'application/vnd.ibm.secure-container': ['sc'],
    'application/vnd.iccprofile': ['icc', 'icm'],
    'application/vnd.igloader': ['igl'],
    'application/vnd.immervision-ivp': ['ivp'],
    'application/vnd.immervision-ivu': ['ivu'],
    'application/vnd.insors.igm': ['igm'],
    'application/vnd.intercon.formnet': ['xpw', 'xpx'],
    'application/vnd.intergeo': ['i2g'],
    'application/vnd.intu.qbo': ['qbo'],
    'application/vnd.intu.qfx': ['qfx'],
    'application/vnd.ipunplugged.rcprofile': ['rcprofile'],
    'application/vnd.irepository.package+xml': ['irp'],
    'application/vnd.is-xpr': ['xpr'],
    'application/vnd.isac.fcs': ['fcs'],
    'application/vnd.jam': ['jam'],
    'application/vnd.jcp.javame.midlet-rms': ['rms'],
    'application/vnd.jisp': ['jisp'],
    'application/vnd.joost.joda-archive': ['joda'],
    'application/vnd.kahootz': ['ktz', 'ktr'],
    'application/vnd.kde.karbon': ['karbon'],
    'application/vnd.kde.kchart': ['chrt'],
    'application/vnd.kde.kformula': ['kfo'],
    'application/vnd.kde.kivio': ['flw'],
    'application/vnd.kde.kontour': ['kon'],
    'application/vnd.kde.kpresenter': ['kpr', 'kpt'],
    'application/vnd.kde.kspread': ['ksp'],
    'application/vnd.kde.kword': ['kwd', 'kwt'],
    'application/vnd.kenameaapp': ['htke'],
    'application/vnd.kidspiration': ['kia'],
    'application/vnd.kinar': ['kne', 'knp'],
    'application/vnd.koan': ['skp', 'skd', 'skt', 'skm'],
    'application/vnd.kodak-descriptor': ['sse'],
    'application/vnd.las.las+xml': ['lasxml'],
    'application/vnd.llamagraphics.life-balance.desktop': ['lbd'],
    'application/vnd.llamagraphics.life-balance.exchange+xml': ['lbe'],
    'application/vnd.lotus-1-2-3': ['123'],
    'application/vnd.lotus-approach': ['apr'],
    'application/vnd.lotus-freelance': ['pre'],
    'application/vnd.lotus-notes': ['nsf'],
    'application/vnd.lotus-organizer': ['org'],
    'application/vnd.lotus-screencam': ['scm'],
    'application/vnd.lotus-wordpro': ['lwp'],
    'application/vnd.macports.portpkg': ['portpkg'],
    'application/vnd.mapbox-vector-tile': ['mvt'],
    'application/vnd.mcd': ['mcd'],
    'application/vnd.medcalcdata': ['mc1'],
    'application/vnd.mediastation.cdkey': ['cdkey'],
    'application/vnd.mfer': ['mwf'],
    'application/vnd.mfmp': ['mfm'],
    'application/vnd.micrografx.flo': ['flo'],
    'application/vnd.micrografx.igx': ['igx'],
    'application/vnd.mif': ['mif'],
    'application/vnd.mobius.daf': ['daf'],
    'application/vnd.mobius.dis': ['dis'],
    'application/vnd.mobius.mbk': ['mbk'],
    'application/vnd.mobius.mqy': ['mqy'],
    'application/vnd.mobius.msl': ['msl'],
    'application/vnd.mobius.plc': ['plc'],
    'application/vnd.mobius.txf': ['txf'],
    'application/vnd.mophun.application': ['mpn'],
    'application/vnd.mophun.certificate': ['mpc'],
    'application/vnd.mozilla.xul+xml': ['xul'],
    'application/vnd.ms-artgalry': ['cil'],
    'application/vnd.ms-cab-compressed': ['cab'],
    'application/vnd.ms-excel': ['xls', 'xlb', 'xlm', 'xla', 'xlc', 'xlt', 'xlw'],
    'application/vnd.ms-excel.addin.macroenabled.12': ['xlam'],
    'application/vnd.ms-excel.sheet.binary.macroenabled.12': ['xlsb'],
    'application/vnd.ms-excel.sheet.macroenabled.12': ['xlsm'],
    'application/vnd.ms-excel.template.macroenabled.12': ['xltm'],
    'application/vnd.ms-fontobject': ['eot'],
    'application/vnd.ms-htmlhelp': ['chm'],
    'application/vnd.ms-ims': ['ims'],
    'application/vnd.ms-lrm': ['lrm'],
    'application/vnd.ms-officetheme': ['thmx'],
    'application/vnd.ms-outlook': ['msg'],
    'application/vnd.ms-pki.seccat': ['cat'],
    'application/vnd.ms-pki.stl': ['stl'],
    'application/vnd.ms-powerpoint': ['ppt', 'pot', 'ppa', 'pps', 'pwz'],
    'application/vnd.ms-powerpoint.addin.macroenabled.12': ['ppam'],
    'application/vnd.ms-powerpoint.presentation.macroenabled.12': ['pptm'],
    'application/vnd.ms-powerpoint.slide.macroenabled.12': ['sldm'],
    'application/vnd.ms-powerpoint.slideshow.macroenabled.12': ['ppsm'],
    'application/vnd.ms-powerpoint.template.macroenabled.12': ['potm'],
    'application/vnd.ms-project': ['mpp', 'mpt'],
    'application/vnd.ms-word.document.macroenabled.12': ['docm'],
    'application/vnd.ms-word.template.macroenabled.12': ['dotm'],
    'application/vnd.ms-works': ['wps', 'wks', 'wcm', 'wdb'],
    'application/vnd.ms-wpl': ['wpl'],
    'application/vnd.ms-xpsdocument': ['xps'],
    'application/vnd.mseq': ['mseq'],
    'application/vnd.musician': ['mus'],
    'application/vnd.muvee.style': ['msty'],
    'application/vnd.mynfc': ['taglet'],
    'application/vnd.neurolanguage.nlu': ['nlu'],
    'application/vnd.nitf': ['ntf', 'nitf'],
    'application/vnd.noblenet-directory': ['nnd'],
    'application/vnd.noblenet-sealer': ['nns'],
    'application/vnd.noblenet-web': ['nnw'],
    'application/vnd.nokia.n-gage.ac+xml': ['ac'],
    'application/vnd.nokia.n-gage.data': ['ngdat'],
    'application/vnd.nokia.n-gage.symbian.install': ['n-gage'],
    'application/vnd.nokia.radio-preset': ['rpst'],
    'application/vnd.nokia.radio-presets': ['rpss'],
    'application/vnd.novadigm.edm': ['edm'],
    'application/vnd.novadigm.edx': ['edx'],
    'application/vnd.novadigm.ext': ['ext'],
    'application/vnd.oasis.opendocument.chart': ['odc'],
    'application/vnd.oasis.opendocument.chart-template': ['otc'],
    'application/vnd.oasis.opendocument.database': ['odb'],
    'application/vnd.oasis.opendocument.formula': ['odf'],
    'application/vnd.oasis.opendocument.formula-template': ['odft'],
    'application/vnd.oasis.opendocument.graphics': ['odg'],
    'application/vnd.oasis.opendocument.graphics-template': ['otg'],
    'application/vnd.oasis.opendocument.image': ['odi'],
    'application/vnd.oasis.opendocument.image-template': ['oti'],
    'application/vnd.oasis.opendocument.presentation': ['odp'],
    'application/vnd.oasis.opendocument.presentation-template': ['otp'],
    'application/vnd.oasis.opendocument.spreadsheet': ['ods'],
    'application/vnd.oasis.opendocument.spreadsheet-template': ['ots'],
    'application/vnd.oasis.opendocument.text': ['odt'],
    'application/vnd.oasis.opendocument.text-master': ['odm'],
    'application/vnd.oasis.opendocument.text-template': ['ott'],
    'application/vnd.oasis.opendocument.text-web': ['oth'],
    'application/vnd.olpc-sugar': ['xo'],
    'application/vnd.oma.dd2+xml': ['dd2'],
    'application/vnd.openblox.game+xml': ['obgx'],
    'application/vnd.openofficeorg.extension': ['oxt'],
    'application/vnd.openstreetmap.data+xml': ['osm'],
    'application/vnd.openxmlformats-officedocument.presentationml.presentation': ['pptx'],
    'application/vnd.openxmlformats-officedocument.presentationml.slide': ['sldx'],
    'application/vnd.openxmlformats-officedocument.presentationml.slideshow': ['ppsx'],
    'application/vnd.openxmlformats-officedocument.presentationml.template': ['potx'],
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': ['xlsx'],
    'application/vnd.openxmlformats-officedocument.spreadsheetml.template': ['xltx'],
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document': ['docx'],
    'application/vnd.openxmlformats-officedocument.wordprocessingml.template': ['dotx'],
    'application/vnd.osgeo.mapguide.package': ['mgp'],
    'application/vnd.osgi.dp': ['dp'],
    'application/vnd.osgi.subsystem': ['esa'],
    'application/vnd.palm': ['pdb', 'pqa', 'oprc'],
    'application/vnd.pawaafile': ['paw'],
    'application/vnd.pg.format': ['str'],
    'application/vnd.pg.osasli': ['ei6'],
    'application/vnd.picsel': ['efif'],
    'application/vnd.pmi.widget': ['wg'],
    'application/vnd.pocketlearn': ['plf'],
    'application/vnd.powerbuilder6': ['pbd'],
    'application/vnd.previewsystems.box': ['box'],
    'application/vnd.proteus.magazine': ['mgz'],
    'application/vnd.publishare-delta-tree': ['qps'],
    'application/vnd.pvi.ptid1': ['ptid'],
    'application/vnd.quark.quarkxpress': ['qxd',
                                        'qxt',
                                        'qwd',
                                        'qwt',
                                        'qxl',
                                        'qxb'],
    'application/vnd.rar': ['rar'],
    'application/vnd.realvnc.bed': ['bed'],
    'application/vnd.recordare.musicxml': ['mxl'],
    'application/vnd.recordare.musicxml+xml': ['musicxml'],
    'application/vnd.rig.cryptonote': ['cryptonote'],
    'application/vnd.rim.cod': ['cod'],
    'application/vnd.rn-realmedia': ['rm'],
    'application/vnd.rn-realmedia-vbr': ['rmvb'],
    'application/vnd.route66.link66+xml': ['link66'],
    'application/vnd.sailingtracker.track': ['st'],
    'application/vnd.seemail': ['see'],
    'application/vnd.sema': ['sema'],
    'application/vnd.semd': ['semd'],
    'application/vnd.semf': ['semf'],
    'application/vnd.shana.informed.formdata': ['ifm'],
    'application/vnd.shana.informed.formtemplate': ['itp'],
    'application/vnd.shana.informed.interchange': ['iif'],
    'application/vnd.shana.informed.package': ['ipk'],
    'application/vnd.simtech-mindmapper': ['twd', 'twds'],
    'application/vnd.smaf': ['mmf'],
    'application/vnd.smart.teacher': ['teacher'],
    'application/vnd.software602.filler.form+xml': ['fo'],
    'application/vnd.solent.sdkm+xml': ['sdkm', 'sdkd'],
    'application/vnd.spotfire.dxp': ['dxp'],
    'application/vnd.spotfire.sfs': ['sfs'],
    'application/vnd.stardivision.calc': ['sdc'],
    'application/vnd.stardivision.draw': ['sda'],
    'application/vnd.stardivision.impress': ['sdd'],
    'application/vnd.stardivision.math': ['smf'],
    'application/vnd.stardivision.writer': ['sdw', 'vor'],
    'application/vnd.stardivision.writer-global': ['sgl'],
    'application/vnd.stepmania.package': ['smzip'],
    'application/vnd.stepmania.stepchart': ['sm'],
    'application/vnd.sun.wadl+xml': ['wadl'],
    'application/vnd.sun.xml.calc': ['sxc'],
    'application/vnd.sun.xml.calc.template': ['stc'],
    'application/vnd.sun.xml.draw': ['sxd'],
    'application/vnd.sun.xml.draw.template': ['std'],
    'application/vnd.sun.xml.impress': ['sxi'],
    'application/vnd.sun.xml.impress.template': ['sti'],
    'application/vnd.sun.xml.math': ['sxm'],
    'application/vnd.sun.xml.writer': ['sxw'],
    'application/vnd.sun.xml.writer.global': ['sxg'],
    'application/vnd.sun.xml.writer.template': ['stw'],
    'application/vnd.sus-calendar': ['sus', 'susp'],
    'application/vnd.svd': ['svd'],
    'application/vnd.symbian.install': ['sis', 'sisx'],
    'application/vnd.syncml+xml': ['xsm'],
    'application/vnd.syncml.dm+wbxml': ['bdm'],
    'application/vnd.syncml.dm+xml': ['xdm'],
    'application/vnd.syncml.dmddf+xml': ['ddf'],
    'application/vnd.tao.intent-module-archive': ['tao'],
    'application/vnd.tcpdump.pcap': ['pcap', 'cap', 'dmp'],
    'application/vnd.tmobile-livetv': ['tmo'],
    'application/vnd.trid.tpt': ['tpt'],
    'application/vnd.triscape.mxs': ['mxs'],
    'application/vnd.trueapp': ['tra'],
    'application/vnd.ufdl': ['ufd', 'ufdl'],
    'application/vnd.uiq.theme': ['utz'],
    'application/vnd.umajin': ['umj'],
    'application/vnd.unity': ['unityweb'],
    'application/vnd.uoml+xml': ['uoml'],
    'application/vnd.vcx': ['vcx'],
    'application/vnd.visio': ['vsd', 'vst', 'vss', 'vsw'],
    'application/vnd.visionary': ['vis'],
    'application/vnd.vsf': ['vsf'],
    'application/vnd.wap.wbxml': ['wbxml'],
    'application/vnd.wap.wmlc': ['wmlc'],
    'application/vnd.wap.wmlscriptc': ['wmlsc'],
    'application/vnd.webturbo': ['wtb'],
    'application/vnd.wolfram.player': ['nbp'],
    'application/vnd.wordperfect': ['wpd'],
    'application/vnd.wqd': ['wqd'],
    'application/vnd.wt.stf': ['stf'],
    'application/vnd.xara': ['xar'],
    'application/vnd.xfdl': ['xfdl'],
    'application/vnd.yamaha.hv-dic': ['hvd'],
    'application/vnd.yamaha.hv-script': ['hvs'],
    'application/vnd.yamaha.hv-voice': ['hvp'],
    'application/vnd.yamaha.openscoreformat': ['osf'],
    'application/vnd.yamaha.openscoreformat.osfpvg+xml': ['osfpvg'],
    'application/vnd.yamaha.smaf-audio': ['saf'],
    'application/vnd.yamaha.smaf-phrase': ['spf'],
    'application/vnd.yellowriver-custom-menu': ['cmp'],
    'application/vnd.zul': ['zir', 'zirz'],
    'application/vnd.zzazz.deck+xml': ['zaz'],
    'application/voicexml+xml': ['voicexml+xml', 'vxml'],
    'application/voucher-cms+json': ['voucher-cms+json'],
    'application/vq-rtcpxr': ['vq-rtcpxr'],
    'application/wasm': ['wasm'],
    'application/watcherinfo+xml': ['watcherinfo+xml', 'wif'],
    'application/webpush-options+json': ['webpush-options+json'],
    'application/whoispp-query': ['whoispp-query'],
    'application/whoispp-response': ['whoispp-response'],
    'application/widget': ['widget', 'wgt'],
    'application/winhlp': ['hlp'],
    'application/wita': ['wita'],
    'application/wordperfect5.1': ['wordperfect5.1'],
    'application/wsdl+xml': ['wsdl+xml', 'wsdl'],
    'application/wspolicy+xml': ['wspolicy+xml', 'wspolicy'],
    'application/x-7z-compressed': ['7z'],
    'application/x-abiword': ['abw'],
    'application/x-ace-compressed': ['ace'],
    'application/x-apple-diskimage': ['dmg'],
    'application/x-arj': ['arj'],
    'application/x-authorware-bin': ['aab', 'x32', 'u32', 'vox'],
    'application/x-authorware-map': ['aam'],
    'application/x-authorware-seg': ['aas'],
    'application/x-bcpio': ['bcpio'],
    'application/x-bdoc': ['bdoc'],
    'application/x-bittorrent': ['torrent'],
    'application/x-blorb': ['blb', 'blorb'],
    'application/x-bzip': ['bz'],
    'application/x-bzip2': ['bz2', 'boz'],
    'application/x-cbr': ['cbr', 'cba', 'cbt', 'cbz', 'cb7'],
    'application/x-cdlink': ['vcd'],
    'application/x-cfs-compressed': ['cfs'],
    'application/x-chat': ['chat'],
    'application/x-chess-pgn': ['pgn'],
    'application/x-chrome-extension': ['crx'],
    'application/x-cocoa': ['cco'],
    'application/x-conference': ['nsc'],
    'application/x-cpio': ['cpio'],
    'application/x-csh': ['csh'],
    'application/x-debian-package': ['deb', 'udeb'],
    'application/x-dgc-compressed': ['dgc'],
    'application/x-director': ['dir',
                            'dcr',
                            'dxr',
                            'cst',
                            'cct',
                            'cxt',
                            'w3d',
                            'fgd',
                            'swa'],
    'application/x-doom': ['wad'],
    'application/x-dtbncx+xml': ['ncx'],
    'application/x-dtbook+xml': ['dtb'],
    'application/x-dtbresource+xml': ['res'],
    'application/x-dvi': ['dvi'],
    'application/x-envoy': ['evy'],
    'application/x-eva': ['eva'],
    'application/x-font-bdf': ['bdf'],
    'application/x-font-ghostscript': ['gsf'],
    'application/x-font-linux-psf': ['psf'],
    'application/x-font-pcf': ['pcf'],
    'application/x-font-snf': ['snf'],
    'application/x-font-type1': ['pfa', 'pfb', 'pfm', 'afm'],
    'application/x-freearc': ['arc'],
    'application/x-futuresplash': ['spl'],
    'application/x-gca-compressed': ['gca'],
    'application/x-glulx': ['ulx'],
    'application/x-gnumeric': ['gnumeric'],
    'application/x-gramps-xml': ['gramps'],
    'application/x-gtar': ['gtar'],
    'application/x-hdf': ['hdf'],
    'application/x-hdf5': ['h5'],
    'application/x-httpd-php': ['php'],
    'application/x-install-instructions': ['install'],
    'application/x-iso9660-image': ['iso'],
    'application/x-iwork-keynote-sffkey': ['key'],
    'application/x-iwork-numbers-sffnumbers': ['numbers'],
    'application/x-iwork-pages-sffpages': ['pages'],
    'application/x-java-archive-diff': ['jardiff'],
    'application/x-java-jnlp-file': ['jnlp'],
    'application/x-keepass2': ['kdbx'],
    'application/x-latex': ['latex'],
    'application/x-lua-bytecode': ['luac'],
    'application/x-lzh-compressed': ['lzh', 'lha'],
    'application/x-makeself': ['run'],
    'application/x-mie': ['mie'],
    'application/x-mif': ['mif'],
    'application/x-mobipocket-ebook': ['prc', 'mobi'],
    'application/x-ms-application': ['application'],
    'application/x-ms-shortcut': ['lnk'],
    'application/x-ms-wmd': ['wmd'],
    'application/x-ms-wmz': ['wmz'],
    'application/x-ms-xbap': ['xbap'],
    'application/x-msaccess': ['mdb'],
    'application/x-msbinder': ['obd'],
    'application/x-mscardfile': ['crd'],
    'application/x-msclip': ['clp'],
    'application/x-msdos-program': ['exe'],
    'application/x-msdownload': ['exe', 'dll', 'com', 'bat', 'msi'],
    'application/x-msmediaview': ['mvb', 'm13', 'm14'],
    'application/x-msmetafile': ['wmf', 'wmz', 'emf', 'emz'],
    'application/x-msmoney': ['mny'],
    'application/x-mspublisher': ['pub'],
    'application/x-msschedule': ['scd'],
    'application/x-msterminal': ['trm'],
    'application/x-mswrite': ['wri'],
    'application/x-netcdf': ['cdf', 'nc'],
    'application/x-ns-proxy-autoconfig': ['pac'],
    'application/x-nzb': ['nzb'],
    'application/x-perl': ['pl', 'pm'],
    'application/x-pilot': ['prc', 'pdb'],
    'application/x-pkcs12': ['p12', 'pfx'],
    'application/x-pkcs7-certificates': ['p7b', 'spc'],
    'application/x-pkcs7-certreqresp': ['p7r'],
    'application/x-pki-message': ['x-pki-message'],
    'application/x-pn-realaudio': ['ram'],
    'application/x-python-code': ['pyc', 'pyo'],
    'application/x-rar-compressed': ['rar'],
    'application/x-redhat-package-manager': ['rpm'],
    'application/x-research-info-systems': ['ris'],
    'application/x-sea': ['sea'],
    'application/x-sh': ['sh'],
    'application/x-shar': ['shar'],
    'application/x-shockwave-flash': ['swf'],
    'application/x-silverlight-app': ['xap'],
    'application/x-sql': ['sql'],
    'application/x-stuffit': ['sit'],
    'application/x-stuffitx': ['sitx'],
    'application/x-subrip': ['srt'],
    'application/x-sv4cpio': ['sv4cpio'],
    'application/x-sv4crc': ['sv4crc'],
    'application/x-t3vm-image': ['t3'],
    'application/x-tads': ['gam'],
    'application/x-tar': ['tar'],
    'application/x-tcl': ['tcl', 'tk'],
    'application/x-tex': ['tex'],
    'application/x-tex-tfm': ['tfm'],
    'application/x-texinfo': ['texi', 'texinfo'],
    'application/x-tgif': ['obj'],
    'application/x-troff': ['roff', 't', 'tr'],
    'application/x-troff-man': ['man'],
    'application/x-troff-me': ['me'],
    'application/x-troff-ms': ['ms'],
    'application/x-ustar': ['ustar'],
    'application/x-virtualbox-hdd': ['hdd'],
    'application/x-virtualbox-ova': ['ova'],
    'application/x-virtualbox-ovf': ['ovf'],
    'application/x-virtualbox-vbox': ['vbox'],
    'application/x-virtualbox-vbox-extpack': ['vbox-extpack'],
    'application/x-virtualbox-vdi': ['vdi'],
    'application/x-virtualbox-vhd': ['vhd'],
    'application/x-virtualbox-vmdk': ['vmdk'],
    'application/x-wais-source': ['src'],
    'application/x-web-app-manifest+json': ['webapp'],
    'application/x-www-form-urlencoded': ['x-www-form-urlencoded'],
    'application/x-x509-ca-cert': ['x-x509-ca-cert', 'der', 'crt', 'pem'],
    'application/x-x509-ca-ra-cert': ['x-x509-ca-ra-cert'],
    'application/x-x509-next-ca-cert': ['x-x509-next-ca-cert'],
    'application/x-xfig': ['fig'],
    'application/x-xliff+xml': ['xlf'],
    'application/x-xpinstall': ['xpi'],
    'application/x-xz': ['xz'],
    'application/x-zmachine': ['z1', 'z2', 'z3', 'z4', 'z5', 'z6', 'z7', 'z8'],
    'application/x400-bp': ['x400-bp'],
    'application/xacml+xml': ['xacml+xml'],
    'application/xaml+xml': ['xaml'],
    'application/xcap-att+xml': ['xcap-att+xml', 'xav'],
    'application/xcap-caps+xml': ['xcap-caps+xml', 'xca'],
    'application/xcap-diff+xml': ['xcap-diff+xml', 'xdf'],
    'application/xcap-el+xml': ['xcap-el+xml', 'xel'],
    'application/xcap-error+xml': ['xcap-error+xml'],
    'application/xcap-ns+xml': ['xcap-ns+xml', 'xns'],
    'application/xcon-conference-info+xml': ['xcon-conference-info+xml'],
    'application/xcon-conference-info-diff+xml': ['xcon-conference-info-diff+xml'],
    'application/xenc+xml': ['xenc+xml', 'xenc'],
    'application/xfdf': ['xfdf'],
    'application/xhtml+xml': ['xhtml+xml', 'xhtml', 'xht'],
    'application/xliff+xml': ['xliff+xml', 'xlf'],
    'application/xml': ['xml', 'xsl', 'rdf', 'wsdl', 'xpdl', 'xsd', 'rng'],
    'application/xml-dtd': ['xml-dtd', 'dtd'],
    'application/xml-external-parsed-entity': ['xml-external-parsed-entity'],
    'application/xml-patch+xml': ['xml-patch+xml'],
    'application/xmpp+xml': ['xmpp+xml'],
    'application/xop+xml': ['xop+xml', 'xop'],
    'application/xproc+xml': ['xpl'],
    'application/xslt+xml': ['xslt+xml', 'xsl', 'xslt'],
    'application/xspf+xml': ['xspf'],
    'application/xv+xml': ['xv+xml', 'mxml', 'xhvml', 'xvml', 'xvm'],
    'application/yang': ['yang'],
    'application/yang-data+cbor': ['yang-data+cbor'],
    'application/yang-data+json': ['yang-data+json'],
    'application/yang-data+xml': ['yang-data+xml'],
    'application/yang-patch+json': ['yang-patch+json'],
    'application/yang-patch+xml': ['yang-patch+xml'],
    'application/yin+xml': ['yin+xml', 'yin'],
    'application/zip': ['zip'],
    'application/zlib': ['zlib'],
    'application/zstd': ['zstd'],
    'audio/1d-interleaved-parityfec': ['1d-interleaved-parityfec'],
    'audio/32kadpcm': ['32kadpcm'],
    'audio/3gpp': ['3gpp', '3gp'],
    'audio/3gpp2': ['3gpp2', '3g2'],
    'audio/aac': ['aac', 'adts', 'loas', 'ass'],
    'audio/ac3': ['ac3'],
    'audio/adpcm': ['adp'],
    'audio/amr': ['amr'],
    'audio/amr-wb': ['amr-wb'],
    'audio/amr-wb+': ['amr-wb+'],
    'audio/aptx': ['aptx'],
    'audio/asc': ['asc'],
    'audio/atrac-advanced-lossless': ['atrac-advanced-lossless'],
    'audio/atrac-x': ['atrac-x'],
    'audio/atrac3': ['atrac3'],
    'audio/basic': ['basic', 'au', 'snd'],
    'audio/bv16': ['bv16'],
    'audio/bv32': ['bv32'],
    'audio/clearmode': ['clearmode'],
    'audio/cn': ['cn'],
    'audio/dat12': ['dat12'],
    'audio/dls': ['dls'],
    'audio/dsr-es201108': ['dsr-es201108'],
    'audio/dsr-es202050': ['dsr-es202050'],
    'audio/dsr-es202211': ['dsr-es202211'],
    'audio/dsr-es202212': ['dsr-es202212'],
    'audio/dv': ['dv'],
    'audio/dvi4': ['dvi4'],
    'audio/eac3': ['eac3'],
    'audio/encaprtp': ['encaprtp'],
    'audio/evrc': ['evrc'],
    'audio/evrc-qcp': ['evrc-qcp'],
    'audio/evrc0': ['evrc0'],
    'audio/evrc1': ['evrc1'],
    'audio/evrcb': ['evrcb'],
    'audio/evrcb0': ['evrcb0'],
    'audio/evrcb1': ['evrcb1'],
    'audio/evrcnw': ['evrcnw'],
    'audio/evrcnw0': ['evrcnw0'],
    'audio/evrcnw1': ['evrcnw1'],
    'audio/evrcwb': ['evrcwb'],
    'audio/evrcwb0': ['evrcwb0'],
    'audio/evrcwb1': ['evrcwb1'],
    'audio/evs': ['evs'],
    'audio/example': ['example'],
    'audio/flexfec': ['flexfec'],
    'audio/fwdred': ['fwdred'],
    'audio/g711-0': ['g711-0'],
    'audio/g719': ['g719'],
    'audio/g722': ['g722'],
    'audio/g7221': ['g7221'],
    'audio/g723': ['g723'],
    'audio/g726-16': ['g726-16'],
    'audio/g726-24': ['g726-24'],
    'audio/g726-32': ['g726-32'],
    'audio/g726-40': ['g726-40'],
    'audio/g728': ['g728'],
    'audio/g729': ['g729'],
    'audio/g7291': ['g7291'],
    'audio/g729d': ['g729d'],
    'audio/g729e': ['g729e'],
    'audio/gsm': ['gsm'],
    'audio/gsm-efr': ['gsm-efr'],
    'audio/gsm-hr-08': ['gsm-hr-08'],
    'audio/ilbc': ['ilbc'],
    'audio/ip-mr_v2.5': ['ip-mr_v2.5'],
    'audio/l16': ['l16'],
    'audio/l20': ['l20'],
    'audio/l24': ['l24'],
    'audio/l8': ['l8'],
    'audio/lpc': ['lpc'],
    'audio/melp': ['melp'],
    'audio/melp1200': ['melp1200'],
    'audio/melp2400': ['melp2400'],
    'audio/melp600': ['melp600'],
    'audio/mhas': ['mhas'],
    'audio/midi': ['mid', 'midi', 'kar', 'rmi'],
    'audio/mobile-xmf': ['mobile-xmf', 'mxmf'],
    'audio/mp3': ['mp3'],
    'audio/mp4': ['mp4', 'm4a', 'mp4a'],
    'audio/mp4a-latm': ['mp4a-latm'],
    'audio/mpa': ['mpa'],
    'audio/mpa-robust': ['mpa-robust'],
    'audio/mpeg': ['mpeg', 'mp3', 'mp2', 'mpga', 'mp2a', 'm2a', 'm3a'],
    'audio/mpeg4-generic': ['mpeg4-generic'],
    'audio/ogg': ['ogg', 'oga', 'spx', 'opus'],
    'audio/opus': ['opus'],
    'audio/parityfec': ['parityfec'],
    'audio/pcma': ['pcma'],
    'audio/pcma-wb': ['pcma-wb'],
    'audio/pcmu': ['pcmu'],
    'audio/pcmu-wb': ['pcmu-wb'],
    'audio/prs.sid': ['prs.sid'],
    'audio/qcelp': ['qcelp'],
    'audio/raptorfec': ['raptorfec'],
    'audio/red': ['red'],
    'audio/rtp-enc-aescm128': ['rtp-enc-aescm128'],
    'audio/rtp-midi': ['rtp-midi'],
    'audio/rtploopback': ['rtploopback'],
    'audio/rtx': ['rtx'],
    'audio/s3m': ['s3m'],
    'audio/scip': ['scip'],
    'audio/silk': ['sil'],
    'audio/smv': ['smv'],
    'audio/smv-qcp': ['smv-qcp'],
    'audio/smv0': ['smv0'],
    'audio/sofa': ['sofa'],
    'audio/sp-midi': ['sp-midi'],
    'audio/speex': ['speex'],
    'audio/t140c': ['t140c'],
    'audio/t38': ['t38'],
    'audio/telephone-event': ['telephone-event'],
    'audio/tetra_acelp': ['tetra_acelp'],
    'audio/tetra_acelp_bb': ['tetra_acelp_bb'],
    'audio/tone': ['tone'],
    'audio/tsvcis': ['tsvcis'],
    'audio/uemclip': ['uemclip'],
    'audio/ulpfec': ['ulpfec'],
    'audio/usac': ['usac'],
    'audio/vdvi': ['vdvi'],
    'audio/vmr-wb': ['vmr-wb'],
    'audio/vnd.dece.audio': ['uva', 'uvva'],
    'audio/vnd.digital-winds': ['eol'],
    'audio/vnd.dra': ['dra'],
    'audio/vnd.dts': ['dts'],
    'audio/vnd.dts.hd': ['dtshd'],
    'audio/vnd.lucent.voice': ['lvp'],
    'audio/vnd.ms-playready.media.pya': ['pya'],
    'audio/vnd.nuera.ecelp4800': ['ecelp4800'],
    'audio/vnd.nuera.ecelp7470': ['ecelp7470'],
    'audio/vnd.nuera.ecelp9600': ['ecelp9600'],
    'audio/vnd.rip': ['rip'],
    'audio/vorbis': ['vorbis'],
    'audio/vorbis-config': ['vorbis-config'],
    'audio/wav': ['wav'],
    'audio/wave': ['wav'],
    'audio/webm': ['weba'],
    'audio/x-aac': ['aac'],
    'audio/x-aiff': ['aif', 'aifc', 'aiff'],
    'audio/x-caf': ['caf'],
    'audio/x-flac': ['flac'],
    'audio/x-m4a': ['m4a'],
    'audio/x-matroska': ['mka'],
    'audio/x-mpegurl': ['m3u'],
    'audio/x-ms-wax': ['wax'],
    'audio/x-ms-wma': ['wma'],
    'audio/x-pn-realaudio': ['ra', 'ram'],
    'audio/x-pn-realaudio-plugin': ['rmp'],
    'audio/x-realaudio': ['ra'],
    'audio/x-wav': ['wav'],
    'audio/xm': ['xm'],
    'chemical/x-cdx': ['cdx'],
    'chemical/x-cif': ['cif'],
    'chemical/x-cmdf': ['cmdf'],
    'chemical/x-cml': ['cml'],
    'chemical/x-csml': ['csml'],
    'chemical/x-xyz': ['xyz'],
    'font/collection': ['collection', 'ttc'],
    'font/otf': ['otf'],
    'font/sfnt': ['sfnt'],
    'font/ttf': ['ttf'],
    'font/woff': ['woff'],
    'font/woff2': ['woff2'],
    'image/aces': ['aces', 'exr'],
    'image/apng': ['apng'],
    'image/avci': ['avci'],
    'image/avcs': ['avcs'],
    'image/avif': ['avif'],
    'image/bmp': ['bmp'],
    'image/cgm': ['cgm'],
    'image/dicom-rle': ['dicom-rle', 'drle'],
    'image/dpx': ['dpx'],
    'image/emf': ['emf'],
    'image/example': ['example'],
    'image/fits': ['fits'],
    'image/g3fax': ['g3fax', 'g3'],
    'image/gif': ['gif'],
    'image/heic': ['heic'],
    'image/heic-sequence': ['heic-sequence', 'heics'],
    'image/heif': ['heif'],
    'image/heif-sequence': ['heif-sequence', 'heifs'],
    'image/hej2k': ['hej2k', 'hej2'],
    'image/hsj2': ['hsj2'],
    'image/ief': ['ief'],
    'image/jls': ['jls'],
    'image/jp2': ['jp2', 'jpg2'],
    'image/jpeg': ['jpg', 'jpe', 'jpeg'],
    'image/jph': ['jph'],
    'image/jphc': ['jphc', 'jhc'],
    'image/jpm': ['jpm'],
    'image/jpx': ['jpx', 'jpf'],
    'image/jxr': ['jxr'],
    'image/jxra': ['jxra'],
    'image/jxrs': ['jxrs'],
    'image/jxs': ['jxs'],
    'image/jxsc': ['jxsc'],
    'image/jxsi': ['jxsi'],
    'image/jxss': ['jxss'],
    'image/ktx': ['ktx'],
    'image/ktx2': ['ktx2'],
    'image/naplps': ['naplps'],
    'image/png': ['png'],
    'image/prs.btif': ['prs.btif', 'btif'],
    'image/prs.pti': ['prs.pti', 'pti'],
    'image/pwg-raster': ['pwg-raster'],
    'image/sgi': ['sgi'],
    'image/svg+xml': ['svg+xml', 'svg', 'svgz'],
    'image/t38': ['t38'],
    'image/tiff': ['tiff', 'tif'],
    'image/tiff-fx': ['tiff-fx', 'tfx'],
    'image/vnd.adobe.photoshop': ['psd'],
    'image/vnd.airzip.accelerator.azv': ['azv'],
    'image/vnd.dece.graphic': ['uvi', 'uvvi', 'uvg', 'uvvg'],
    'image/vnd.djvu': ['djvu', 'djv'],
    'image/vnd.dvb.subtitle': ['sub'],
    'image/vnd.dwg': ['dwg'],
    'image/vnd.dxf': ['dxf'],
    'image/vnd.fastbidsheet': ['fbs'],
    'image/vnd.fpx': ['fpx'],
    'image/vnd.fst': ['fst'],
    'image/vnd.fujixerox.edmics-mmr': ['mmr'],
    'image/vnd.fujixerox.edmics-rlc': ['rlc'],
    'image/vnd.microsoft.icon': ['ico'],
    'image/vnd.ms-dds': ['dds'],
    'image/vnd.ms-modi': ['mdi'],
    'image/vnd.ms-photo': ['wdp'],
    'image/vnd.net-fpx': ['npx'],
    'image/vnd.pco.b16': ['b16'],
    'image/vnd.tencent.tap': ['tap'],
    'image/vnd.valve.source.texture': ['vtf'],
    'image/vnd.wap.wbmp': ['wbmp'],
    'image/vnd.xiff': ['xif'],
    'image/vnd.zbrush.pcx': ['pcx'],
    'image/webp': ['webp'],
    'image/wmf': ['wmf'],
    'image/x-3ds': ['3ds'],
    'image/x-cmu-raster': ['ras'],
    'image/x-cmx': ['cmx'],
    'image/x-freehand': ['fh', 'fhc', 'fh4', 'fh5', 'fh7'],
    'image/x-icon': ['ico'],
    'image/x-jng': ['jng'],
    'image/x-mrsid-image': ['sid'],
    'image/x-ms-bmp': ['bmp'],
    'image/x-pcx': ['pcx'],
    'image/x-pict': ['pic', 'pct'],
    'image/x-portable-anymap': ['pnm'],
    'image/x-portable-bitmap': ['pbm'],
    'image/x-portable-graymap': ['pgm'],
    'image/x-portable-pixmap': ['ppm'],
    'image/x-rgb': ['rgb'],
    'image/x-tga': ['tga'],
    'image/x-xbitmap': ['xbm'],
    'image/x-xpixmap': ['xpm'],
    'image/x-xwindowdump': ['xwd'],
    'message/bhttp': ['bhttp'],
    'message/cpim': ['cpim'],
    'message/delivery-status': ['delivery-status'],
    'message/disposition-notification': ['disposition-notification'],
    'message/example': ['example'],
    'message/feedback-report': ['feedback-report'],
    'message/global': ['global', 'u8msg'],
    'message/global-delivery-status': ['global-delivery-status', 'u8dsn'],
    'message/global-disposition-notification': ['global-disposition-notification',
                                                'u8mdn'],
    'message/global-headers': ['global-headers', 'u8hdr'],
    'message/http': ['http'],
    'message/imdn+xml': ['imdn+xml'],
    'message/mls': ['mls'],
    'message/ohttp-req': ['ohttp-req'],
    'message/ohttp-res': ['ohttp-res'],
    'message/rfc822': ['eml', 'mht', 'mhtml', 'nws', 'mime'],
    'message/sip': ['sip'],
    'message/sipfrag': ['sipfrag'],
    'message/tracking-status': ['tracking-status'],
    'message/vnd.wfa.wsc': ['wsc'],
    'model/3mf': ['3mf'],
    'model/e57': ['e57'],
    'model/example': ['example'],
    'model/gltf+json': ['gltf+json', 'gltf'],
    'model/gltf-binary': ['gltf-binary', 'glb'],
    'model/iges': ['iges', 'igs'],
    'model/jt': ['jt'],
    'model/mesh': ['msh', 'mesh', 'silo'],
    'model/mtl': ['mtl'],
    'model/obj': ['obj'],
    'model/prc': ['prc'],
    'model/step': ['step'],
    'model/step+xml': ['step+xml', 'stpx'],
    'model/step+zip': ['step+zip', 'stpz'],
    'model/step-xml+zip': ['step-xml+zip', 'stpxz'],
    'model/stl': ['stl'],
    'model/u3d': ['u3d'],
    'model/vnd.collada+xml': ['dae'],
    'model/vnd.dwf': ['dwf'],
    'model/vnd.gdl': ['gdl'],
    'model/vnd.gtw': ['gtw'],
    'model/vnd.mts': ['mts'],
    'model/vnd.opengex': ['ogex'],
    'model/vnd.parasolid.transmit.binary': ['x_b'],
    'model/vnd.parasolid.transmit.text': ['x_t'],
    'model/vnd.sap.vds': ['vds'],
    'model/vnd.usdz+zip': ['usdz'],
    'model/vnd.valve.source.compiled-map': ['bsp'],
    'model/vnd.vtu': ['vtu'],
    'model/vrml': ['wrl', 'vrml'],
    'model/x3d+binary': ['x3db', 'x3dbz'],
    'model/x3d+fastinfoset': ['x3d+fastinfoset', 'x3db'],
    'model/x3d+vrml': ['x3dv', 'x3dvz'],
    'model/x3d+xml': ['x3d+xml', 'x3d', 'x3dz'],
    'model/x3d-vrml': ['x3d-vrml', 'x3dv'],
    'multipart/appledouble': ['appledouble'],
    'multipart/byteranges': ['byteranges'],
    'multipart/encrypted': ['encrypted'],
    'multipart/example': ['example'],
    'multipart/form-data': ['form-data'],
    'multipart/header-set': ['header-set'],
    'multipart/multilingual': ['multilingual'],
    'multipart/related': ['related'],
    'multipart/report': ['report'],
    'multipart/signed': ['signed'],
    'multipart/voice-message': ['voice-message'],
    'multipart/x-mixed-replace': ['x-mixed-replace'],
    'text/1d-interleaved-parityfec': ['1d-interleaved-parityfec'],
    'text/cache-manifest': ['cache-manifest', 'appcache', 'manifest'],
    'text/calendar': ['calendar', 'ics', 'ifb'],
    'text/coffeescript': ['coffee', 'litcoffee'],
    'text/cql': ['cql'],
    'text/cql-expression': ['cql-expression'],
    'text/cql-identifier': ['cql-identifier'],
    'text/css': ['css'],
    'text/csv': ['csv'],
    'text/csv-schema': ['csv-schema'],
    'text/dns': ['dns'],
    'text/encaprtp': ['encaprtp'],
    'text/example': ['example'],
    'text/fhirpath': ['fhirpath'],
    'text/flexfec': ['flexfec'],
    'text/fwdred': ['fwdred'],
    'text/gff3': ['gff3'],
    'text/grammar-ref-list': ['grammar-ref-list'],
    'text/hl7v2': ['hl7v2'],
    'text/html': ['html', 'htm', 'shtml'],
    'text/jade': ['jade'],
    'text/javascript': ['javascript'],
    'text/jcr-cnd': ['jcr-cnd'],
    'text/jsx': ['jsx'],
    'text/less': ['less'],
    'text/markdown': ['markdown', 'md'],
    'text/mathml': ['mml'],
    'text/mdx': ['mdx'],
    'text/mizar': ['mizar'],
    'text/n3': ['n3'],
    'text/parameters': ['parameters'],
    'text/parityfec': ['parityfec'],
    'text/plain': ['txt',
                'bat',
                'c',
                'cs',
                'h',
                'ksh',
                'pl',
                'srt',
                'text',
                'conf',
                'def',
                'list',
                'log',
                'in',
                'ini'],
    'text/provenance-notation': ['provenance-notation'],
    'text/prs.fallenstein.rst': ['prs.fallenstein.rst'],
    'text/prs.lines.tag': ['prs.lines.tag', 'dsc'],
    'text/prs.prop.logic': ['prs.prop.logic'],
    'text/raptorfec': ['raptorfec'],
    'text/red': ['red'],
    'text/rfc822-headers': ['rfc822-headers'],
    'text/richtext': ['rtx'],
    'text/rtf': ['rtf'],
    'text/rtp-enc-aescm128': ['rtp-enc-aescm128'],
    'text/rtploopback': ['rtploopback'],
    'text/rtx': ['rtx'],
    'text/sgml': ['sgml', 'sgm'],
    'text/shaclc': ['shaclc'],
    'text/shex': ['shex'],
    'text/slim': ['slim', 'slm'],
    'text/spdx': ['spdx'],
    'text/strings': ['strings'],
    'text/stylus': ['stylus', 'styl'],
    'text/t140': ['t140'],
    'text/tab-separated-values': ['tab-separated-values', 'tsv'],
    'text/troff': ['troff', 't', 'tr', 'roff', 'man', 'me', 'ms'],
    'text/turtle': ['turtle', 'ttl'],
    'text/ulpfec': ['ulpfec'],
    'text/uri-list': ['uri-list', 'uri', 'uris', 'urls'],
    'text/vcard': ['vcard'],
    'text/vnd.curl': ['curl'],
    'text/vnd.curl.dcurl': ['dcurl'],
    'text/vnd.curl.mcurl': ['mcurl'],
    'text/vnd.curl.scurl': ['scurl'],
    'text/vnd.dvb.subtitle': ['sub'],
    'text/vnd.familysearch.gedcom': ['ged'],
    'text/vnd.fly': ['fly'],
    'text/vnd.fmi.flexstor': ['flx'],
    'text/vnd.graphviz': ['gv'],
    'text/vnd.in3d.3dml': ['3dml'],
    'text/vnd.in3d.spot': ['spot'],
    'text/vnd.sun.j2me.app-descriptor': ['jad'],
    'text/vnd.wap.wml': ['wml'],
    'text/vnd.wap.wmlscript': ['wmls'],
    'text/vtt': ['vtt'],
    'text/wgsl': ['wgsl'],
    'text/x-asm': ['s', 'asm'],
    'text/x-c': ['c', 'cc', 'cxx', 'cpp', 'h', 'hh', 'dic'],
    'text/x-component': ['htc'],
    'text/x-fortran': ['f', 'for', 'f77', 'f90'],
    'text/x-handlebars-template': ['hbs'],
    'text/x-java-source': ['java'],
    'text/x-lua': ['lua'],
    'text/x-markdown': ['mkd'],
    'text/x-nfo': ['nfo'],
    'text/x-opml': ['opml'],
    'text/x-org': ['org'],
    'text/x-pascal': ['p', 'pas'],
    'text/x-processing': ['pde'],
    'text/x-python': ['py'],
    'text/x-sass': ['sass'],
    'text/x-scss': ['scss'],
    'text/x-setext': ['etx'],
    'text/x-sfv': ['sfv'],
    'text/x-sgml': ['sgm', 'sgml'],
    'text/x-suse-ymp': ['ymp'],
    'text/x-uuencode': ['uu'],
    'text/x-vcalendar': ['vcs'],
    'text/x-vcard': ['vcf'],
    'text/xml': ['xml'],
    'text/xml-external-parsed-entity': ['xml-external-parsed-entity'],
    'text/yaml': ['yaml', 'yml'],
    'video/1d-interleaved-parityfec': ['1d-interleaved-parityfec'],
    'video/3gpp': ['3gpp', '3gp'],
    'video/3gpp-tt': ['3gpp-tt'],
    'video/3gpp2': ['3gpp2', '3g2'],
    'video/av1': ['av1'],
    'video/bmpeg': ['bmpeg'],
    'video/bt656': ['bt656'],
    'video/celb': ['celb'],
    'video/dv': ['dv'],
    'video/encaprtp': ['encaprtp'],
    'video/example': ['example'],
    'video/ffv1': ['ffv1'],
    'video/flexfec': ['flexfec'],
    'video/h261': ['h261'],
    'video/h263': ['h263'],
    'video/h263-1998': ['h263-1998'],
    'video/h263-2000': ['h263-2000'],
    'video/h264': ['h264'],
    'video/h264-rcdo': ['h264-rcdo'],
    'video/h264-svc': ['h264-svc'],
    'video/h265': ['h265'],
    'video/h266': ['h266'],
    'video/iso.segment': ['iso.segment', 'm4s'],
    'video/jpeg': ['jpeg', 'jpgv'],
    'video/jpeg2000': ['jpeg2000'],
    'video/jpm': ['jpm', 'jpgm'],
    'video/jxsv': ['jxsv'],
    'video/mj2': ['mj2', 'mjp2'],
    'video/mp1s': ['mp1s'],
    'video/mp2p': ['mp2p'],
    'video/mp2t': ['mp2t', 'ts'],
    'video/mp4': ['mp4', 'mp4v', 'mpg4'],
    'video/mp4v-es': ['mp4v-es'],
    'video/mpeg': ['mpeg', 'm1v', 'mpa', 'mpe', 'mpg', 'm2v'],
    'video/mpeg4-generic': ['mpeg4-generic'],
    'video/mpv': ['mpv'],
    'video/nv': ['nv'],
    'video/ogg': ['ogg', 'ogv'],
    'video/parityfec': ['parityfec'],
    'video/pointer': ['pointer'],
    'video/quicktime': ['quicktime', 'mov', 'qt'],
    'video/raptorfec': ['raptorfec'],
    'video/raw': ['raw'],
    'video/rtp-enc-aescm128': ['rtp-enc-aescm128'],
    'video/rtploopback': ['rtploopback'],
    'video/rtx': ['rtx'],
    'video/scip': ['scip'],
    'video/smpte291': ['smpte291'],
    'video/smpte292m': ['smpte292m'],
    'video/ulpfec': ['ulpfec'],
    'video/vc1': ['vc1'],
    'video/vc2': ['vc2'],
    'video/vnd.dece.hd': ['uvh', 'uvvh'],
    'video/vnd.dece.mobile': ['uvm', 'uvvm'],
    'video/vnd.dece.pd': ['uvp', 'uvvp'],
    'video/vnd.dece.sd': ['uvs', 'uvvs'],
    'video/vnd.dece.video': ['uvv', 'uvvv'],
    'video/vnd.dvb.file': ['dvb'],
    'video/vnd.fvt': ['fvt'],
    'video/vnd.mpegurl': ['mxu', 'm4u'],
    'video/vnd.ms-playready.media.pyv': ['pyv'],
    'video/vnd.uvvu.mp4': ['uvu', 'uvvu'],
    'video/vnd.vivo': ['viv'],
    'video/vp8': ['vp8'],
    'video/vp9': ['vp9'],
    'video/webm': ['webm'],
    'video/x-f4v': ['f4v'],
    'video/x-fli': ['fli'],
    'video/x-flv': ['flv'],
    'video/x-m4v': ['m4v'],
    'video/x-matroska': ['mkv', 'mk3d', 'mks'],
    'video/x-mng': ['mng'],
    'video/x-ms-asf': ['asf', 'asx'],
    'video/x-ms-vob': ['vob'],
    'video/x-ms-wm': ['wm'],
    'video/x-ms-wmv': ['wmv'],
    'video/x-ms-wmx': ['wmx'],
    'video/x-ms-wvx': ['wvx'],
    'video/x-msvideo': ['avi'],
    'video/x-sgi-movie': ['movie'],
    'video/x-smv': ['smv'],
    'x-conference/x-cooltalk': ['ice']
}